### ISSUE TITLE
Next CRAN release

### ISSUE THREAD

**Issue by jgabry** [stan-dev/bayesplot#109]
I'd like to do another CRAN release relatively soon so that the parallel coordinates plot is available. We use it in [a paper](https://arxiv.org/abs/1709.01449) that just went up on arXiv so it would be nice to get that in the CRAN version before too long. 

Here's my checklist of things to do before the release:

* [x] Get the `mcmc_parcoord` PR merged as soon as everyone is happy with it (https://github.com/stan-dev/bayesplot/pull/108)
* [x] Update the NEWS file with stuff that's already been added since previous release (several `_data` functions that @tjmahr added, some minor fixes, etc.)
* [x] Add @tjmahr to the DESCRIPTION file
* [x] Fix #105  (looks like @tjmahr is on top of this)
* [x] Add divergences to `mcmc_scatter` (PR #112)
* [x] Check R release and R devel on win-builder 
* [x] Rebuild online doc

So not too much that needs to get done, but I might be forgetting something. 

@tjmahr if you want to try get the `mcmc_dens_ridges` and similar functions in 
for this next release that's fine too but I think it's also fine to wait for a subsequent
release if it would feel rushed to get them in for this one.

**Comment by tjmahr** [comment]
I think we need to iron out some final aesthetic tweaks for the mcmc_dens_ridges first. It can skip this release.

**Comment by jgabry** [comment]
Ok yeah probably best to wait on that.

**Comment by jgabry** [comment]
Adding to the checklist: 

* [ ] Fix #105  (looks like @tjmahr is on top of this)

**Comment by jgabry** [comment]
@tjmahr If there's nothing you can think of that we should definitely put in the next release, then I'll go ahead start the release process. By that I mean I'll run R CMD CHECK again locally, then check on win-builder (release and devel),  and assuming that's all fine I'll submit to CRAN and update the pkgdown documentation.

**Comment by tjmahr** [comment]
This sounds good!

**Comment by jgabry** [comment]
Actually I noticed there's something weird happening in Mac build from the
last release on CRAN:

https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/bayesplot-00check.html

It seems to have resulted in the binary for El Capitan staying at v1.2
while for everything else it's v1.3:

https://cran.r-project.org/web/packages/bayesplot/index.html

It looks like there's an error in a test (that I can't reproduce locally)
and a warning about pandoc. I thought the CRAN macs were up to date with
pandoc but I guess maybe not.

**Comment by jgabry** [comment]
Ok I think it's in ok enough shape for release. It passed fine on win-builder, locally my mac, and apparently a few times on travis. I just submitted. Will tag the release when accepted.

**Comment by jgabry** [comment]
@tjmahr Just tagged the release: https://github.com/stan-dev/bayesplot/releases/tag/v1.4.0
